# Generated by Django 4.0.4 on 2022-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscreation', '0002_newslink_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newslink',
            options={},
        ),
    ]
